name: todo_lopes
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.10.0
  auto_size_text: ^3.0.0
  google_sign_in: ^6.1.0
  firebase_auth: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/quicksand/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/quicksand/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/quicksand/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/quicksand/Quicksand-Bold.ttf
          weight: 700
